### ISSUE TITLE
Filtteröinti funktio

### ISSUE THREAD

**Issue by jokukayttajanimi** [Agora-Analytica/prototyyppi#30]
Funktio joka filtteröi näkyville tietyn vaalipiirin ehdokkaat ja/tai vain tiettyjen puolueiden ehdokkaat.
Jäljelle jääville ehdokkaille katsotaan keskenään uudet linkit lasketuissa etäisyyksissä heitä lähimpänä oleviin  ehdokkaisiin.

**Comment by isoteemu** [comment]
1: Funktio, joka kerää sekä puoluueet sekä vaalipiirit nodes.json datasta. Kutsu sitä main.html tiedostossa kohdassa, jossa d3 on ladannut `nodes.json` tiedoston.
2: Luo html esitys puolueista ja vaalipiireistä.
3: Lisää käsittelijä, joka huomaa kun jokin luodun listan elementeistä valitaan.
4: Kutsu funktiota joka kertoo graphille uudet arvot - vaikkapa `update_graph_data()`

**Comment by isoteemu** [comment]
13b5b3b on nyt placeholderit. Vaatii varsinaisen implementaation.
