### ISSUE TITLE
Ehdokas Dialogi-ikkuna

### ISSUE THREAD

**Issue by jokukayttajanimi** [Agora-Analytica/prototyyppi#31]
Ehdokas Dialogi-ikkunan toteutus.
-mitä tietoja halutaan näkyville?
-ainakin minimize ja close toiminnot

**Comment by isoteemu** [comment]
#6 #21

**Comment by isoteemu** [comment]
Muuta dialogia niin, että se ei kysele ehdokkaan tietoja palvelimelta, vaan etsii ehdokkaan nodes -listasta ja käyttää sen tarjoamia tietoja. Sitä rakennetta voidaan sitten buildin ohessa tarvittaessa laajentaa.
