### ISSUE TITLE
Webbisivu: Sivun pohjan luonti ja suunnittelu

### ISSUE THREAD

**Issue by Kyrmy** [Agora-Analytica/prototyyppi#6]
Webbisivun rungon luonti ja yleinen suunnittelu.

**Comment by isoteemu** [comment]
Yliopiston tarjoama kurssi aiheesta: [TIEA2120 Web-käyttöliittymien ohjelmointi (5 op)](http://appro.mit.jyu.fi/tiea2120/)

**Comment by isoteemu** [comment]
Repositoryssä on nyt tiedosto agora_analytica/templates/main.html johon voi alkaa sivua rakentelemaan. Siinä tällä hetkellä olevasta (3bff12b) voi tuhota kaiken. Vähintä mitä **pitää** tehdä on päivitää käytetty d3 -versio.

Ja jotta asiat eivät olisi liian helppoja, tulisi käyttää [Jinja2 templatejärjestelmää](https://jinja.palletsprojects.com). Staattisia tiedostoja ei vielä ole sijoitettu mihinkään, ja niiden kohde tulee riippumaan #12 totueutuksesta.

**Comment by isoteemu** [comment]
Sivupohja on pull request #18 myötä `agora_analytica/flask/templates/main.html` -tiedostossa. `agora_analytica/flask/static` -kansioon voi sijoittaa staattisia tiedostoja. `instance/` kansiossa on datatiedostot, mutta niihin ei pääse suoraan vaan ne on määritelty nyt [routeina](https://flask.palletsprojects.com/en/1.1.x/quickstart/#routing) `agoran_analytica/flask/views.py` tiedostossa.

**Comment by isoteemu** [comment]
Sanna kanssa täytyy koordinoida, kuinka tieto palvelimen ja sivun välillä välittyy. #21

**Comment by isoteemu** [comment]
CSS tiedostot käyttävät nyt [Sassia](https://sass-lang.com/). Tämä tarkoittaa, ettei enää muokata `agora_analytics/flask/static/css` -kansiossa olevia `.css` tiedostoja, vaan `agora_analytics/flask/static/scss` -kansiossa olevia `.scss` -tiedostoja. Niissä voi käyttää css syntaksia ihan kuten ennenkin, joten ei tarvitse uutta sen suhteen opetella. Ne kuitenkin pitää muuntaa CSS tiedostoiksi. Jos palvelimelle on asennettu `libsass`, palvelin osaa muuntaa ne lennossa -> `(.venv) $ pip install libsass`. On myös muita sovelluksia niiden kääntämiseksi.

**Comment by Kyrmy** [comment]
@isoteemu Selvä, mitäs hyötyä tuosta SASS:sta on niin kuin käytännössä? Mistä ero tulee ihan tavalliseen CSS:n?

Lisäkyssärinä vielä, mikäli ehdit vain vastata, että miten saisin toteutettua filtterit noille puolueille ja vaalipiireille? Eli tavoitteena olisi saada vain nuo ruksittujen puolueiden/vaalipiirien tiedot ja filtteröidä data niiden perusteella ja mudostaa graafi uudelleen.

Itsellä pushaamaton uudempi versio tuosta omassa forkissa, mutta toteutus on jotenkin vaikea itselle tehdä kun en oikein tiedä miten "kävisin läpi" nuo html:ssä luodut elementit ja suodattaisin datan ja siihen päälle vielä se graafin luonti uudestaan. Varmaan ainakin erillinen main.js jossa luodaan ohjelma johon mennään "hae" nappia painamalla, mutta siitä eteenäpin vähän nihkeää.

Eli jos olisi jotain neuvoa antaa miten tässä pääsisi eteenpäin niin olisi loistavaa, kun en itse ole löytänyt oikein netin avulla mitään tutotoriaalia tai vastaavaa vaikka kuinka yrittänyt etsiä.

**Comment by Kyrmy** [comment]
Lisäksi huomasin että kun yritän käyttää flaskia, niin uusin versio projektista antaa seuraavanlaista erroria. Edellinen toimi ongelmitta.
`ModuleNotFoundError: No module named 'flask_babel'`

**Comment by isoteemu** [comment]
Se sass on sellainen esikääntäjä. Esmes. css ei tarjoa mitään periytyvyyttä, tai luokkien laajentelua. sassilla pystyy määritteleemään periytyvyyksiä, muuttujia ja funktioita, jotka se sitten muuttaa paljaaksi css:i. Eli ei teknisesti mitään, mutta ihmisyyden kannalta ylläpidettävyyttä ja muokattavuutta. Yksinkertainen esimerkki; Jos haluaa pikkaisen leveämmäksi jonkin palkin, voi sassilla kirjoittaa: `width: 5px * 1.2`, eikä tarvitse ruveta itse miettimään paljonko se tekee, tai kommenteissa selittelemään ettei se ole typo, vaikka muualla on 5px ja tässä 6px.

Kirjoitin jo code reviewissä jotain miten haluaisit ehkä lähestyä. Ajatus oli sinulla siinä jotakuinkin oikea;
- Kun valintanappien tila muuttuu, muuttunut tila lähetetään palvelimelle. Kaavojen käsittelystä tekstejä jotka on pakko kandin papereita varten lukea: http://appro.mit.jyu.fi/tiea2120/ohjaus/ohjaus2/  http://appro.mit.jyu.fi/tiea2120/ohjaus/ohjaus3/.
- Palvelin palauttaa sopivat linkit ja solmut.
- palautetut linkit ja solmut kerrotaan graphille. d3:sessa on tätä varten `.data()` funktiot. Joskin sen kutsuminen olisi hyvä piilottaa jonkin abstraktion taakse, jos haluat sitä graph.js tiedostoa lähteä muokkaamaan. Nyt linkkien ja solmujen lisääminen on osa graaffin alustusta, mutta mitään perustetta miksei se alustus olisi erillään solmujen ja linkkine lisäämisen suhteen, ei ole.
- Debuggausta varten olen jo lisännyt sinne `graph.reset()` -funktion, joka aloittaa graphin simuloinnin "alusta". Tätä kutsutaan sitten lopuksi.

**Comment by isoteemu** [comment]
Ajankäytön syistä kokisin, että se filttereiden saattaminen toimintaa 16. päivään mennessä ei ole niin tärkeää. Aina voidaan vain sanoa että käytetään vielä satunnaisdataa syystä X, eikä kukaan jää sitä sen enempää prototyyppiasteella kaipaamaan. Sen sijaan se ehdokastietojen katselu pitäisi tässä parissa viikossa saada toimimaan. Graphissa on nyt [kohta johon voi liittää](https://github.com/Agora-Analytica/prototyyppi/blob/5ba1a0ea3fff9267ed061bdcd07c75ebc61bf0fa/agora_analytica/flask/static/graph.js#L200) ehdokastietojen katselufunktion. Voin sen vaikka sitten lisätä, mutta sitä varten tarvitaan javascript funtio joka avaa sen tietoikkunan. Vaikkapa main.js tiedostossa ``show_node_info(id) { ... }``. Bootrapissa on sitten jotain modaleita ja tooltippejä valmiina, joita voit käyttää sitten em. funktion toteutuksessa.

Yksinkertaisin toteutustapa voisi olla, että palvelin renderöisi sen ehdokkaan tiedot - ie. tekisi siitä sivun - ja se sitten sijoitettaisiin sitten bootsrapin modaali-ikkunan sisällöksi.
1: Solmua klikattaessa `show_node_info(id)` pyytää palvelinta palauttamaan ehdokkaan tiedot
2: backendin `views.py` tiedostoon uusi funktio joka ottaa parametrinä ehdokkaan indexin (/ numeron).
3: funktio tabuloi tarvittavat tiedot, ja syöttää sen templatelle
3: Template renderöi halutun näköisen sivun
4: ehdokkaan renderöity sivu palautetaan selaimelle, ja sijoitetaan sopivaan dialogiin.

@sanmarj on katsonut tuota backend -osuutta, ja @jokukayttajanimi on varmaan myös hyvä käry miten se datasetti on rakennettu, ja mitä siinä on saatavilla.
