### ISSUE TITLE
GDPR rajoitukset

### ISSUE THREAD

**Issue by isoteemu** [Agora-Analytica/prototyyppi#7]
GDPR saattaa rajoittaa voimakkaasti mitä voidaan tehdä. Pitäisi selvittää.

**Comment by isoteemu** [comment]
Yksi vaihtoehto voisi olla, ettei virallisesti pyritä osoittamaan vaikka Teuvo Hakkaraista paskaksi ukoksi datan perusteella, vaan Teuvo Hakkarainen on paska ukko koska sovellus vain pyrkii näennäisesti loukkaamaan.

**Comment by Kyrmy** [comment]
Lueskelin [Finlexistä GDPR](https://www.finlex.fi/fi/esitykset/he/2018/20180009):stä, mutta ainakin oman ymmärykseni mukaan emme voi käyttää dataa sellaisenaan joka yksilöi vastaukset henkilöihin. En tiedä voisiko [luvun 5 §27](https://www.finlex.fi/fi/esitykset/he/2018/20180009#idp448280640) "Henkilötietojen käsittely journalistisen, akateemisen, taiteellisen tai kirjallisen ilmaisun tarkoituksia varten" käyttää hyödyksi, valitettavasti teksti ainakin minulle vähän vaikeasti ymmärrettävää kun en ole lakimies.

Ehdotan siis varmuuden vuoksi, että tehdään siten että julkinen versio ei sisällä yksilöivää dataa. 

Toinen vaihtoehto tietysti olisi että käyttäjä itse syöttäisi luetavan datan, mutta se vaatisi luultavasti datan lukemisen muokkausta ja eikä sovelluksemme ei enää olisi tietysti enää vaalikoneen datan visualisointia.
